---
- name: ansible playbook publishing and promoting content views
  hosts: all
  #hosts: localhost
  #connection: local

  pre_tasks:
    - name: updates | include global variables
      include_vars: global_vars.yml
      tags: always

  roles:
    - { role: promote, content_view: 'CCV RHEL 7', lifecycle_env: 'Development' }
