---
- name: ansible playbook promoting Acceptance to preivous lifecycle version
  hosts: all

  pre_tasks:
    - name: updates | include global variables
      include_vars: global_vars.yml
      tags: always

  roles:
    - { role: promote, content_view: 'CCV RHEL 7', lifecycle_env: 'Acceptance' }
