---
- name: ansible playbook publishing all content views
  hosts: all

  pre_tasks:
    - name: updates | include global variables
      include_vars: global_vars.yml
      tags: always

  roles:
    - publish # without variables, this will publish everything
