---
- name: ansible playbook publishing and promoting content views
  hosts: all
  #hosts: localhost
  #connection: local

  pre_tasks:
    - name: updates | include global variables
      include_vars: global_vars.yml
      tags: always
#    - name: updates | invoke 'Download OVAL Report' job template
#      command: /bin/hammer job-invocation create --job-template "Download OVAL Report" --search-query "name={{ sat_fqdn }}" --async
#      tags: always


  roles:
    - publish # without variables, this will publish everything
# I should capture the content view and lifecycle information here and put it in
# a file that each role can reference.  this should be done after the publish
# but before the promotions.  That might mean a simple role to collect data?
# ...unfortunately, each hammer command may be specific to a content view or
# lifecycle env...
#    - { role: promote, content_view: "{{ content_views }}", lifecycle_env: "{{ lifecycle_envs }}" }
    - { role: promote, content_view: 'CCV RHEL 7', lifecycle_env: 'Production' }
    - { role: promote, content_view: 'CCV RHEL 7', lifecycle_env: 'Acceptance' }
    - { role: promote, content_view: 'CCV RHEL 7', lifecycle_env: 'Development' }
#    - { role: promote, content_view: 'CCV CloudForms', lifecycle_env: 'CloudForms Sandbox' }
#    - { role: promote, content_view: 'CCV RCloudForms', lifecycle_env: 'CloudForms Production' }
