---
# standalone tasks file for publish

################################################################################
# VARIABLES:
#  This will be passed a standalone content view ID to publish
- name: standalone | set fact from passed variables
  set_fact: 'cv={{ cvNAME }}'

- name: standalone | publishing the {{ cv }} content view
  command: hammer content-view publish {{ORGID}} --name "{{cv}}"
           --description "Update {{ ansible_date_time.iso8601 }}"
  
# For some reason ^this^ gives a timeout error even if it is running, so don't
# stop on error. And sometimes it gives an error about the task already running

#- name: standalone | get the Satellite Task Id for the newest publish task
#  shell: hammer --csv task list --search publish --order 'ENDED AT' |
#         awk -F, '!/^ID/ && $6~/planning|running/ {print $1; exit;}'
#  register: satTASK
#  until: satTASK.stdout != ""
#  retries: 5
#  delay: 30

#- name: standalone | wait for the {{ cv }} publish task to complete successfully
#  shell: hammer --csv task list --search {{ satTASK.stdout }} |
#         awk -F, '!/^ID/ && $7 !~ /success/ {print;}'
#  register: result
#  until: result.stdout == ""
#  retries: 5
#  delay: 300
