---
# tasks file for promote

- name: promote | capture all content views in json
  shell: hammer --output json lifecycle-environment list {{ORGID}}
  register: cvsINFO

- name: promote | capture all version info for {{ content_view }} lifecycles
  shell: hammer --output json content-view version list {{ORGID}}
         --content-view "{{ content_view }}"
  register: cvVERS

- name: set_fact | find lifecycle prior to {{ lifecycle_env }}
  set_fact:
    lcID:    "{{ item.ID }}"
    lcPRIOR: "{{ item.Prior }}"
  when: item.Name == lifecycle_env
  with_items: "{{ cvsINFO.stdout }}"

- name: set_fact | find content view version ID related to prior lifecycle [{{lcPRIOR}}]
  set_fact:
    cvPRIORID:  "{{ item.ID }}"
    cvPRIORVER: "{{ item.Version }}"
  when: lcPRIOR in item["Lifecycle Environments"]
  with_items: "{{ cvVERS.stdout }}"

- name: promoting {{ content_view }} version {{ cvPRIORVER }} to {{ lifecycle_env }}
  command: hammer content-view version promote {{ORGID}}
           --id {{cvPRIORID}} --to-lifecycle-environment {{lifecycle_env}}
           --description "Promote {{ ansible_date_time.iso8601 }}"

# add section to skip setting version if version is passed
